name: Publish Package

on:
  push:
    branches:
    - 'github-actions'
    paths-ignore:
    - 'docs/**'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:

  publish:
    runs-on: 'windows-latest'

    steps:
    - uses: actions/checkout@v1

    - name: Run MySQL 8.0 Docker container
      run: docker run -v "$(Get-Location)/server:/etc/mysql/conf.d:ro" -p $33060:3306 --name mysql -e MYSQL_ROOT_PASSWORD='test' mysql:8.0.19 --log-bin-trust-function-creators=1 --local-infile=1 --secure-file-priv=/var/tmp --max-connections=250 --default-authentication-plugin=mysql_native_password

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Unit Tests
      run: dotnet test --configuration Release tests\MySqlConnector.Tests --no-build --no-restore

    - name: Wait for Docker container
      run: |
        for ($i = 1; $i -le 10; $i++)
        {
          mysql -P33060 -uroot -ptest -e "SELECT 1;"
        }

    - name: Conformance Tests
      run: dotnet test --configuration Release tests\Conformance.Tests --no-build --no-restore
      env:
        CONNECTION_STRING: "Server=localhost;Port=33060;User Id=root;Password=test;SSL Mode=None"

    - name: Pack
      run: dotnet pack --configuration Release --no-build --no-restore --version-suffix $(Get-Date -Format "'preview'yyyyMMddHHmmss'+${{ github.sha }}'")

    - name: Install NuGet
      run: choco install nuget.commandline

    - name: Add NuGet source
      run: nuget sources Add -Name "GPR" -Source "https://nuget.pkg.github.com/mysql-net/index.json" -UserName bgrainger -Password ${{ secrets.GITHUB_TOKEN }}

    - name: Publish packages
      run: |
        $files = Get-ChildItem -Path src -Filter *.nupkg -Recurse
        foreach ($file in $files) {
          nuget push $file -Source GPR
        }
